### ISSUE TITLE
issue with football life

### ISSUE THREAD

**Issue by feel2death** [eskay993/gamefiles#1]
im sorry if its not place to asking you about fb life in lutris
but i have game already installed on my hard drive (2nd partition) and i just point the lutris to fl_start. exe 
now my problem is my game somehow start somehow its not just stuck at silder is there any way to make it run flawless or just reinstall using ur guide ?
hope you reply soon thank you

**Comment by eskay993** [comment]
Sorry for the late reply. Haven't been checking the issues here.

It's hard to say what has gone wrong wrong without more info, so might be easiest to start fresh with a new install. Backup your save first as described [here](https://github.com/eskay993/gamefiles/tree/main/sp-football-life-2023#save-file-location-plus-warning).
