### ISSUE TITLE
Football Life 23 script

### ISSUE THREAD

**Issue by Dialatech2303** [eskay993/gamefiles#10]
I get to step 13, I click Next and leave everything default and then exit. After that, I get an error saying the following 

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Settings_b.dll' or one of its dependencies. Module not found.
   at Settings.SettingsForm..ctor()
   at Settings.Program.Main()
Monitored process exited.
Initial process has exited (return code: 20992)
Exit with return code 20992

The settings windows never appear and the only option I have is to click on Abort. If I click on abort it obviously cancels the install and no game is installed.

**Comment by eskay993** [comment]
Thanks for flagging. Seems there is an issue launching `Settings.exe` during the install process with recent flatpak versions of Lutris (including on Steam Deck). Launching `Settings.exe` after installing the game still works fine though, which is odd.

I've updated the script to use a workaround. It now uses pre-configured settings files and skips running `Settings.exe` entirely. You now just select the resolution you want during the install, and the script will handle the rest, including setting the game to fullscreen. Give this version a try:

https://github.com/eskay993/gamefiles/raw/main/sp-football-life-2023/sp-football-life-2023-win.zip
