### ISSUE TITLE
SP Football Life 2023: Steam Deck Issue with SD as a controller

### ISSUE THREAD

**Issue by samti182** [eskay993/gamefiles#11]
Hello!

Script worked fine for me, thx for job and effort !!  but when i go to play, game doesnt recognize my Steam Deck as a controller

The only way I found is with this " trick ":

"_In Gaming Mode:
( WITH A REAL CONTROLLED CONNECTED ) 
go to library select your non-steam game On the right side of the screen is a controller icon and a gear. Click the controller icon

You'll be presented with your current layout. At the top of the screen, make sure you have the external controller selected.

You'll see View Layout, Edit Layout, and a gear in a line. Select the Gear here

The pop up menu is where you'll find Disable Steam Input. You won't find it if you are tabbed onto the Steam Deck as the controller.
"

But when I disconnect controller also my SD stop working as controller
Works fine with this "trick" but I have to get a controller connected even to play with Steam Deck as a controller
There is another way to play with Steam deck as controller witouth having connected PS Pad?

**Comment by eskay993** [comment]
Continued thread on redit:

https://www.reddit.com/r/WEPES/comments/yps9ev/comment/jllp3h8/?context=4

**Comment by samti182** [comment]
worked reinstalling LOVE LOVE 
ty for caring and helping <3
at the end was the easiest solution lol
