### ISSUE TITLE
Closing SP football life 23 on Steam Deck freezes

### ISSUE THREAD

**Issue by elkinjosetm** [eskay993/gamefiles#13]
Hi!

Thanks for the script, everything worked like a charm, except for a weird issue that is happening when closing the game from game options (exit option), the app closes but a white pop up show up with the message "Sider for Pro Evolution Soccer 2021" and never finishes, I have to manually close the game from steam overlay.

I'm on gaming mode.

**Comment by eskay993** [comment]
The game exe launches Sider first before the main game. Sider is used to loads certain mods. It's supposed to close when you exit the game, but I noticed it doesn't always. Not sure if is specific to Wine/Lutris/Linux/Steam Deck, or if this happens on Windows too. When I have time I can look into.

I personally close all my games from the steam overlay anyway so I suggest you do that for now. It will close both the game and Sider when you do it that way.

**Comment by elkinjosetm** [comment]
Thanks for the response, yes, that's what I've been doing, closing it from the overlay.
