### ISSUE TITLE
Conflict with previous installation. 

### ISSUE THREAD

**Issue by darroniz** [eskay993/gamefiles#14]
**Details:**

I installed SP Life 23 with this script and it works like a charm. 

For the first installation I used the internal Steam deck memory. But as I wanted to install other face packs, stadiums, etc, I needed much more space, so I uninstalled the game to install it later on the SD card memory. 

I did the uninstall from Lutris, but the game shortcut still appeared on Steam in game mode. 

I did a second installation, now on the SD card, and after doing the whole installation it doesn't appear in Lutris. In Steam game mode the shortcut still appears but when I click on play it doesn't start. 

I guess there should be a way to delete all the data and start from 0 to avoid conflicts between installations.

**Comment by eskay993** [comment]
When you remove / uninstall a game from Lutris, you should get an option to delete the files. If you choose yes, then it completely wipes the game files (and your saves so be carefull!). I don't believe it removes the shortcut from Steam, so you may need to manually remove it before installing again.

Not sure why the game is not appearing in Lutris after installing to SD Card.  Can you see the game files in your SD Card? If they can, manually delete them and try again. 

Also, make sure Lutris has access to the SD Card. If you haven't;t given it access using something like Flatseal, then have a look [here](https://github.com/eskay993/gamefiles/issues/4#issuecomment-1468783257) for instructions.
