### ISSUE TITLE
It didn’t install the game, it showed errors! 

### ISSUE THREAD

**Issue by Husamfa** [eskay993/gamefiles#16]
**Details:**

- Which game are you trying to install?
Football life 2024

- What platform/distro are you trying it on (e.g. Steam Deck)?
Lutris, Steam deck

**Issue Description:**
It didn’t install the game at all. Even though at the end it says installation completed but it says there was some errors. I tried clearing Lutris cache files after I followed you instruction and tried again to install it, it failed.
Matter of fact, I downloaded the previous version (FL2023, by Lutris on the same steam deck and worked fabulous, and I still have it installed and still playable). 

_Please provide details of what steps you followed when the issue occurred:_
I followed what as what the guide provides. But at the step number 9, where it says:
“You may get a popup asking you to install mono. Just click cancel if you do” I actually pressed install (not cancel). I hope this is not case

**Error Log:**
Command exited with code 13568
Also
Command exited with Code 7936

_If you got an error message, please paste the full log here (not just the error code)._
I got this message:
SP Football Life 2024 has not been totally installed because of the following reason:
Uninstall FL24.exe: This file contains invalid data.

**Comment by eskay993** [comment]
Thanks for the info. Just to confirm, did you make it all the way to the end before seeing that error? So you want through the full game install, selected your choice from the switcher tool and then got the error?

If so, I suspect you might have corrupted install files. I've never see an error before about corrupt data, and the fact that the 2023 script works for you makes me think there is something wrong with the actual install files. Try download the game again and trying. 

Also, doesn't really matter if you installed mono. The script uninstalls mono anyway, so clicking cancel just saved you time by not downloading it.

**Comment by samti182** [comment]
same prob here : Command exited with code 13568 at steam deck
At pc working fine
