### ISSUE TITLE
SP Football Life 2024 - Lutris failed to retrieve wine (wine-ge-8-17-x86_64) information

### ISSUE THREAD

**Issue by RaymondYouTube** [eskay993/gamefiles#17]
Hello. I need help. I installed the .yami script. But when I tried to install the game where I clicked the create a Steam shortcut check, it just gave me an error message that Lutris failed to retrieve wine (wine-ge-8-17-x86_64) information. I tried every version of Wine-GE I had for Lutris. I even have lutris-GE-Proton8-17-x86_64. Never got it to work. Is there a fix to this?

**Comment by eskay993** [comment]
Saw reddit you resolved it by changing the proton version. Glad it's working now.

https://www.reddit.com/r/SPFootballLife/comments/16wxn0z/comment/k5377pg/?utm_source=share&utm_medium=web2x&context=3
