### ISSUE TITLE
Cannot switch player while running

### ISSUE THREAD

**Issue by L1so** [eskay993/gamefiles#22]
Hello, I don't if this a bug or no, but I cannot switch player while running (L + R1) trying to get the ball, the player have to stop or walk first then i can change the player, this does not happen on my windows 11 running fl 24.

**Comment by L1so** [comment]
Ah it seems to be controller issue, the lt/rt button registered as z axis in lutris joystick test

**Comment by eskay993** [comment]
Sorry missed this. This is a separate issue to Lutris or the game so not sure how much I can help. If you're controller is not xinput (like an Xbox controller) then try playing the game through Steam and use Steam Input.

**Comment by L1so** [comment]
I'm using regular usb gamepad

**Comment by eskay993** [comment]
Sorry, not sure. I would suggest checking Linux forums / subs for help with you particular controller as this is not a game or script issue.
