### ISSUE TITLE
Lutris not installing

### ISSUE THREAD

**Issue by ChunkyLoverMark** [eskay993/gamefiles#25]
**Details:**

- Which game are you trying to install?
SP Football Life 2024

- What platform/distro are you trying it on (e.g. Steam Deck)?
Steam Deck

**Issue Description:**

Following this guide: https://www.reddit.com/r/SPFootballLife/comments/16wxn0z/guide_sp_football_life_2024_on_steam_deck/ the game is playable but doesn't save to steam and doesn't show as a saved game in Lutris. Doesn't finish in Lutris and have to abort to leave even though game is playable in a window.

**Error Log:**

Started initial process 229 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended remove_mono win7
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20230212-next, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: 2d7770aa1f49f42ad9dafb092110dbf49fa6581738f6b80488cf0d7f59b2de72 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win64
Executing w_do_call remove_mono
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono
------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call win7
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_win7
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine winecfg -v win7
------------------------------------------------------
warning: Running /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/deck/Games/sp-football-life-2024 terminate
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
Started initial process 1290 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/sp-football-life-2024/dotnet/NDP46-KB3045557-x86-x64-AllOS-ENU.exe /q /norestart
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows8-RT-KB3045562-x86.cab...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows8.1-KB3045563-x86.cab...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\x64-Windows8-RT-KB3045562-x64.cab...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\x64-Windows8.1-KB3045563-x64.cab...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_core_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_core_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_extended_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_extended_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx451\netfx_Full_GDR_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx452\netfx_Full_GDR_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx451\netfx_Full_GDR_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx452\netfx_Full_GDR_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx451\netfx_Full_LDR_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx452\netfx_Full_LDR_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx451\netfx_Full_LDR_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx452\netfx_Full_LDR_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx45\netfx_Full_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_Full_x64.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\NetFx45\netfx_Full_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_Full_x86.msi...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\header.bmp...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\SplashScreen.bmp...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\watermark.bmp...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\DisplayIcon.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Print.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate1.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate10.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate2.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate3.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate4.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate5.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate6.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate7.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate8.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Rotate9.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Save.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\Setup.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\stop.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\SysReqMet.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\SysReqNotMet.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Graphics\warn.ico...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2052\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1028\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1025\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1033\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1030\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\3082\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1029\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1031\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1032\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1042\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1041\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1037\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1053\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1035\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1046\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1044\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1043\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1040\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1049\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2070\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1038\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1045\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1036\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1055\LocalizedData.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\ParameterInfo.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Strings.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\UiInfo.xml...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\SetupUi.xsd...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\DHtmlHeader.html...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1025\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1028\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1030\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1029\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1032\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1033\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1035\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1036\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1038\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1043\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1044\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1045\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1041\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1042\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1031\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1046\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1053\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1049\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1055\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1037\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1040\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\3082\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2052\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2070\eula.rtf...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Setup.exe...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\SetupUtility.exe...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\SetupEngine.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1028\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2052\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1042\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1041\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1037\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1025\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1033\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1044\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1029\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1030\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1035\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1040\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1046\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1045\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1031\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\2070\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\3082\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1036\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1038\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1043\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1032\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1053\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1055\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\1049\SetupResources.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\SetupUi.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\sqmapi.dll...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows6.0-KB956250-v6001-x64.msu...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows6.0-KB956250-v6001-x86.msu...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows6.1-KB958488-v6001-x64.msu...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\Windows6.1-KB958488-v6001-x86.msu...

Preparing: C:\fd34c65e694b27f6d465d11a3ab0\netfx_Full.mzz...

Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 3303 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/sp-football-life-2024/vcrun_x86/vc_redist.x86.exe /silent /norestart
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 3469 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/sp-football-life-2024/vcrun_x64/vc_redist.x64.exe /silent /norestart
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 3637 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended win10
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20230212-next, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: 2d7770aa1f49f42ad9dafb092110dbf49fa6581738f6b80488cf0d7f59b2de72 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win64
Executing w_do_call win10
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_win10
Executing /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine winecfg -v win10
------------------------------------------------------
warning: Running /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/deck/Games/sp-football-life-2024 terminate
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
Started initial process 4655 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/deck/Downloads/Games/PES23/SPFL23re/SPFL23_setup.exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Initial process has exited (return code: 0)

**Comment by eskay993** [comment]
Thanks for the logs. Everything looks ok (you can ignore all the warnings). It looks like you are running `SPFL23_setup.exe` not the 2024 setup exe. The script expect folders created by the 2024 installer so that might be the issue. Try again with the 2024 setup exe and see how that goes.

**Comment by ChunkyLoverMark** [comment]
Thanks for getting back to me so quickly, yeah you're right, works perfectly with the 2024 files thank you 🙏

**Comment by eskay993** [comment]
Great. Glad it;s working.
