### ISSUE TITLE
65280

### ISSUE THREAD

**Issue by narkisose** [eskay993/gamefiles#38]
**Details:**

- Which game are you trying to install?
  SPFL 2025

- What platform/distro are you trying it on (e.g. Steam Deck)?
Steamdeck OLED

**Issue Description:**

<Command exited with code 65280>

_Please provide details of what steps you followed when the issue occurred:_

it happened when i tried to install SPFL2025.
![IMG_4275](https://github.com/user-attachments/assets/805688e3-251e-45d4-9ae6-4391c243d91a)

**Error Log:**

```

_If you got an error message, please paste the full log here (not just the error code)._

Please help me;;)
``
![IMG_4275](https://github.com/user-attachments/assets/37aca399-594a-4797-a1db-87969f7ca0fe)

**Comment by eskay993** [comment]
I can't help without more info. I need the full log when the error occurs, not just the error code, and details about what step you were on and what you were doing.
