### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by anisiovalverde** [eskay993/gamefiles#9]
After finish all the game works, but I can't open settings to change the resolution, so I have a black bar on top, Settings.exe open shows on screen and then closes, also the setting file for steam deck is not working, I think that is related to the update 3.20

**Comment by eskay993** [comment]
Do you mean a small black bars at top and bottom of the screen? If so, that's normal. The game supports 16:9 so it won't fill up the whole screen. 

If you're playing on Deck and in Game Mode then you don't really need to change anything is Settings so you should be fine.
